/*

  Created by David Spooner

*/

import TreeSitter


/// A wrapper for the tree-sitter's *TSLanguage* struct.
public struct TSLanguage {
  /// The address of the TSLanguage structure given on initialization. Note that the content is statically allocated.
  let ptr : OpaquePointer

  /// Initlialize an instance with the result of the `tree_sitter_MyLang` function generated by tree-sitter in `parser.c`.
  public init(_ p: OpaquePointer) {
    ptr = p
  }
}
