#!/bin/bash

# Create and sign an xcframework bundle containing a version of libtree_sitter_cli.a
# for each macos supported architecture.

# Set default option values
TREE_SITTER=

# Get specified option values
while [[ $# -gt 0 ]]; do
    case $1 in
      -l|--tree-sitter)
          # the location of the tree-sitter working copy
          TREE_SITTER="$2"; shift; shift
          if [[ ! -d $TREE_SITTER ]]; then
              echo "no such directory: $TREE_SITTER"
              exit 1
          fi;;
      -*)
          echo "invalid option: $1"
          exit 1;;
      *)
          echo "invalid argument: $1"
          exit 1;;
    esac
done

# Attempt to find the tree-sitter checkout if unspecified.
if [[ $TREE_SITTER == "" ]]; then
    DEFAULT_DIRS=(.. $PWD/.build/checkouts)
    for DIR in $DEFAULT_DIRS; do
        if [[ -d $DIR/tree-sitter ]]; then
            TREE_SITTER=$DIR/tree-sitter
            break
        fi
    done
    if [ $TREE_SITTER == "" ]; then
        echo "can't infer location of tree-sitter checkout"
        exit 1
    fi
fi

# TODO: param defaulting to release
CONFIGURATION=debug

MANIFEST_PATH=${TREE_SITTER}/cli/Cargo.toml
LIB_NAME=libtree_sitter_cli.a
INCLUDE=${TREE_SITTER}/cli/include
TARGET_DIR=${PWD}/.build/cargo
UNIVERSAL_LIB=${TARGET_DIR}/${LIB_NAME}
FRAMEWORK=${PWD}/XCFrameworks/TreeSitterCLI.xcframework

set -x

# Build for each platform
rm -rf ${TARGET_DIR}
cargo rustc --manifest-path ${MANIFEST_PATH} --lib --crate-type=staticlib --target-dir ${TARGET_DIR} --target aarch64-apple-darwin
cargo rustc --manifest-path ${MANIFEST_PATH} --lib --crate-type=staticlib --target-dir ${TARGET_DIR} --target  x86_64-apple-darwin

# Combine as a universal binary
lipo ${TARGET_DIR}/aarch64-apple-darwin/${CONFIGURATION}/${LIB_NAME} ${TARGET_DIR}/x86_64-apple-darwin/${CONFIGURATION}/${LIB_NAME} -create -output ${UNIVERSAL_LIB}

# Bundle as an Xcode framework
if [ -d ${FRAMEWORK} ]; then rm -rf ${FRAMEWORK}; fi
xcodebuild -create-xcframework -library ${UNIVERSAL_LIB} -headers ${INCLUDE} -output ${FRAMEWORK}

# Sign the bundle
codesign --timestamp -s "Apple Development:" ${FRAMEWORK}
